export const state = {
  refreshTimer: null,
  preflightTimer: null,
  tokenRefreshTimer: null,
  servers: [],
  databaseStatus: null,
  deploymentDoctor: null,
  modelProfiles: {},
  jobs: [],
  lastAutoManifestRoot: "",
  latestEligibility: null,
  remoteWorkerTargets: [],
  workerScaleTarget: null,
  jobsPage: {
    offset: 0,
    limit: 50,
    status: "all",
    includeArchived: false,
    lastCount: 0,
    total: 0,
    hasMore: false
  },
  openWorkerDetails: new Set(),
  openJobDetails: new Set(),
  shardInspectors: new Map(),
  manifestIntegrity: new Map(),
  manifestFreezeReports: new Map(),
  shardAttempts: new Map(),
  jobLogs: new Map(),
  recentErrors: new Map()
};
