export const state = {
  refreshTimer: null,
  preflightTimer: null,
  tokenRefreshTimer: null,
  servers: [],
  databaseStatus: null,
  deploymentDoctor: null,
  modelProfiles: {},
  jobs: [],
  lastAutoManifestRoot: "",
  latestEligibility: null,
  remoteWorkerTargets: [],
  workerScaleTarget: null,
  jobsPage: {
    offset: 0,
    limit: 50,
    status: "all",
    includeArchived: false,
    lastCount: 0,
    total: 0,
    hasMore: false
  },
  openWorkerDetails: new Set(),
  openJobDetails: new Set(),
  shardInspectors: new Map(),
  manifestIntegrity: new Map(),
  manifestFreezeReports: new Map(),
  shardAttempts: new Map(),
  jobLogs: new Map(),
  recentErrors: new Map()
};
export const ui = {
  controlApiToken: document.getElementById("controlApiToken"),
  refreshHint: document.getElementById("refreshHint"),
  opsQueueSummary: document.getElementById("opsQueueSummary"),
  opsAttentionSummary: document.getElementById("opsAttentionSummary"),
  opsWorkerSummary: document.getElementById("opsWorkerSummary"),
  opsReadinessSummary: document.getElementById("opsReadinessSummary"),
  databaseStatus: document.getElementById("databaseStatus"),
  deploymentDoctorStatus: document.getElementById("deploymentDoctorStatus"),
  serverMessage: document.getElementById("serverMessage"),
  jobMessage: document.getElementById("jobMessage"),
  jobsMessage: document.getElementById("jobsMessage"),
  executionMode: document.getElementById("executionMode"),
  preflightMetrics: document.getElementById("preflightMetrics"),
  serverMetrics: document.getElementById("serverMetrics"),
  modelProfile: document.getElementById("modelProfile"),
  apiKey: document.getElementById("apiKey"),
  resolvedModelConfig: document.getElementById("resolvedModelConfig"),
  profileLabel: document.getElementById("profileLabel"),
  profileEngine: document.getElementById("profileEngine"),
  profileIp: document.getElementById("profileIp"),
  profilePort: document.getElementById("profilePort"),
  profileModelName: document.getElementById("profileModelName"),
  profilePageConcurrency: document.getElementById("profilePageConcurrency"),
  profileExtraArgs: document.getElementById("profileExtraArgs"),
  profileApiKey: document.getElementById("profileApiKey"),
  profileApiKeyEnvVar: document.getElementById("profileApiKeyEnvVar"),
  profileHasApiKey: document.getElementById("profileHasApiKey"),
  profileRequiresApiKey: document.getElementById("profileRequiresApiKey"),
  profileClearApiKey: document.getElementById("profileClearApiKey"),
  profileIsDefault: document.getElementById("profileIsDefault"),
  modelProfileMessage: document.getElementById("modelProfileMessage"),
  workerScope: document.getElementById("workerScope"),
  singleWorkerField: document.getElementById("singleWorkerField"),
  singleWorkerSelect: document.getElementById("singleWorkerSelect"),
  selectedWorkersField: document.getElementById("selectedWorkersField"),
  selectedWorkersList: document.getElementById("selectedWorkersList"),
  selectedWorkersPanel: document.getElementById("selectedWorkersPanel"),
  manualWorkerIds: document.getElementById("manualWorkerIds"),
  manualWorkersPanel: document.getElementById("manualWorkersPanel"),
  serversBody: document.getElementById("serversBody"),
  remoteWorkerTarget: document.getElementById("remoteWorkerTarget"),
  remoteWorkerHost: document.getElementById("remoteWorkerHost"),
  remoteWorkerSshUser: document.getElementById("remoteWorkerSshUser"),
  remoteWorkerServerId: document.getElementById("remoteWorkerServerId"),
  remoteWorkerServiceUser: document.getElementById("remoteWorkerServiceUser"),
  remoteWorkerServiceGroup: document.getElementById("remoteWorkerServiceGroup"),
  remoteWorkerRepoDir: document.getElementById("remoteWorkerRepoDir"),
  remoteWorkerControlUrl: document.getElementById("remoteWorkerControlUrl"),
  remoteWorkerSharedRoots: document.getElementById("remoteWorkerSharedRoots"),
  remoteWorkerServiceAction: document.getElementById("remoteWorkerServiceAction"),
  remoteWorkerOutput: document.getElementById("remoteWorkerOutput"),
  workerScaleHost: document.getElementById("workerScaleHost"),
  workerScaleSshUser: document.getElementById("workerScaleSshUser"),
  workerScaleCurrentCount: document.getElementById("workerScaleCurrentCount"),
  workerScaleTargetCount: document.getElementById("workerScaleTargetCount"),
  workerScaleServerIdPrefix: document.getElementById("workerScaleServerIdPrefix"),
  workerScaleSeedServerId: document.getElementById("workerScaleSeedServerId"),
  workerScaleRepoDir: document.getElementById("workerScaleRepoDir"),
  workerScaleServiceUser: document.getElementById("workerScaleServiceUser"),
  workerScaleServiceGroup: document.getElementById("workerScaleServiceGroup"),
  workerScaleSharedRoots: document.getElementById("workerScaleSharedRoots"),
  workerScaleResult: document.getElementById("workerScaleResult"),
  jobsBody: document.getElementById("jobsBody"),
  jobStatusFilter: document.getElementById("jobStatusFilter"),
  jobPageSize: document.getElementById("jobPageSize"),
  includeArchivedJobs: document.getElementById("includeArchivedJobs"),
  previousJobsBtn: document.getElementById("previousJobsBtn"),
  nextJobsBtn: document.getElementById("nextJobsBtn"),
  jobsPageInfo: document.getElementById("jobsPageInfo")
};
