ALTER TABLE servers
ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;

ALTER TABLE model_profiles
ADD COLUMN IF NOT EXISTS api_key_env_var VARCHAR(255);

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS failure_category VARCHAR(64);

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS model_profile_id VARCHAR(128);

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS manifest_root TEXT;

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS target_files_per_shard INTEGER NOT NULL DEFAULT 1000;

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS max_shard_attempts INTEGER NOT NULL DEFAULT 3;

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS allowed_server_ids_json TEXT NOT NULL DEFAULT '[]';

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;

ALTER TABLE work_shards
ADD COLUMN IF NOT EXISTS lease_expires_at TIMESTAMPTZ;

ALTER TABLE work_shards
ADD COLUMN IF NOT EXISTS api_inflight INTEGER NOT NULL DEFAULT 0;

ALTER TABLE work_shards
ADD COLUMN IF NOT EXISTS api_inflight_peak INTEGER NOT NULL DEFAULT 0;

ALTER TABLE work_shards
ADD COLUMN IF NOT EXISTS api_waiting INTEGER NOT NULL DEFAULT 0;

ALTER TABLE work_shards
ADD COLUMN IF NOT EXISTS oldest_api_inflight FLOAT NOT NULL DEFAULT 0;

ALTER TABLE work_shards
ADD COLUMN IF NOT EXISTS execution_paused BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE work_shards
ADD COLUMN IF NOT EXISTS api_concurrency_limit INTEGER;

ALTER TABLE work_shards
ADD COLUMN IF NOT EXISTS execution_control_reason TEXT;

ALTER TABLE manifests
ADD COLUMN IF NOT EXISTS next_shard_index INTEGER NOT NULL DEFAULT 1;

ALTER TABLE manifests
ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ;

ALTER TABLE manifests
ADD COLUMN IF NOT EXISTS freeze_report_json TEXT NOT NULL DEFAULT '{}';

ALTER TABLE scan_units
ADD COLUMN IF NOT EXISTS failure_category VARCHAR(64);

ALTER TABLE job_counters
ADD COLUMN IF NOT EXISTS recent_errors_json TEXT NOT NULL DEFAULT '[]';

INSERT INTO schema_migrations (version)
VALUES ('0009_compatibility_schema_columns')
ON CONFLICT (version) DO NOTHING;
